//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicWarehouse.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Device
    {
        public int ID { get; set; }
        public string IMEI { get; set; }
        public int DeviceTypeID { get; set; }
        public System.DateTime ReceivedDateProvider { get; set; }
        public string Status { get; set; }
    
        public virtual A_DeviceType A_DeviceType { get; set; }
    }
}
