//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicWarehouse.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_DevicesHistory
    {
        public int ID { get; set; }
        public int CurrentCenterID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int DeviceID { get; set; }
    }
}
