//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicWarehouse.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Employee
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Phone { get; set; }
        public string JobTitle { get; set; }
        public int Store_ID { get; set; }
        public System.DateTime JoinningDate { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual A_Store A_Store { get; set; }
    }
}
