//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicWarehouse.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Center
    {
        public int Id { get; set; }
        public Nullable<int> Level { get; set; }
        public string CentralName { get; set; }
        public string CenterName { get; set; }
        public string OwnerName { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Email { get; set; }
        public string CommNo { get; set; }
        public string TaxNo { get; set; }
        public Nullable<short> Active { get; set; }
        public string Cat { get; set; }
        public string Last_Cat { get; set; }
        public Nullable<System.DateTime> ChgTime { get; set; }
        public Nullable<bool> AllowTransfeer { get; set; }
        public Nullable<int> user_created { get; set; }
        public Nullable<System.DateTime> added_date { get; set; }
        public string region { get; set; }
        public string sales_person { get; set; }
        public string national_id { get; set; }
        public string activity { get; set; }
        public string sim_no { get; set; }
        public string Deal_way { get; set; }
        public Nullable<bool> is_agent { get; set; }
        public string govern { get; set; }
        public string Mobile2 { get; set; }
        public Nullable<int> inserted { get; set; }
        public Nullable<int> Sales_id { get; set; }
        public string Machine_Type { get; set; }
        public string Total { get; set; }
        public string Paid { get; set; }
        public string Remain { get; set; }
        public string Date_To { get; set; }
        public Nullable<int> UserUpdate { get; set; }
        public string MachineCode { get; set; }
        public string edDesc { get; set; }
        public Nullable<bool> Logged_In { get; set; }
        public Nullable<System.DateTime> Last_login { get; set; }
        public Nullable<System.DateTime> last_logout { get; set; }
        public string last_channel { get; set; }
        public Nullable<bool> Web { get; set; }
        public Nullable<bool> Api { get; set; }
        public Nullable<float> Total_Amount { get; set; }
        public Nullable<double> Total_Points { get; set; }
        public string Serial { get; set; }
        public string Simno { get; set; }
        public string region_mina { get; set; }
        public Nullable<int> Place_Id { get; set; }
        public Nullable<int> sales_center_id { get; set; }
        public Nullable<float> Balance_cash { get; set; }
        public Nullable<decimal> last1month { get; set; }
        public Nullable<decimal> last2month { get; set; }
        public Nullable<decimal> last3month { get; set; }
        public Nullable<decimal> last0month { get; set; }
        public Nullable<int> Centers_company_Id { get; set; }
        public Nullable<int> Parent_CenterID { get; set; }
        public Nullable<float> Total_Parent_Amount { get; set; }
        public Nullable<bool> ProfitDailyControl { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> AccountProfileID { get; set; }
        public Nullable<int> EntityID { get; set; }
        public Nullable<bool> TransferTree { get; set; }
        public Nullable<int> CountResetPassword { get; set; }
        public Nullable<int> Batch { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<int> GovernID { get; set; }
    }
}
